### PR TITLE
My portfolio moblie Using JS DOM and events

### PR DESCRIPTION
**Pull request by AbdelazizSoliman**
In this project, I learned the following:-
- Using basic JavaScript syntax.
- Using JavaScript to manipulate DOM elements.
- Using JavaScript events.

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @AbdelazizSoliman, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a PR description and has linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by MahmoudBakr23 — COMMENTED** [review]
# Hi team😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please add a descriptive README file

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Review by Reem-lab — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the file for javascript linters so kindly add the eslint file and update the linters.yml file to have the js linters as well 💯♻🔥 please check this link [HTML CSS JS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js)

- I can see your README is not complete so kindly complete the missing parts as well to make it completed 🔥♻💯✅

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AbdelazizSoliman** [comment]
@Reem-lab please let me create another pull request.

**Pull request merged**
